version: '3'
services:
  mongo:
    hostname: mongo
    image: mongo:3.6
    ports:
      - "27017:27017"

  spring_api:
    hostname: spring_api
    build: .
    image: spring_api:compose
    ports:
      - "8080:8080"
    depends_on:
      - mongo
networks:
  default:
    external:
      name: ultra-network
